shared ParashaMap = let
    ParashaMap = {
        {"Achrei Mot", "Acharei Mos"},
        {"Achrei Mot-Kedoshim", "Acharei Mos-Kedoshim"},
        {"Balak", "Balak"},
        {"Bamidbar", "Bamidbar"},
        {"Bechukotai", "Bechukosai"},
        {"Beha'alotcha", "Beha'aloscha"},
        {"Beha’aloscha", "Beha'aloscha"},
        {"Beha’alotcha", "Beha'aloscha"},
        {"Beha'aloscha", "Beha'aloscha"},
        {"Beha’aloscha", "Beha'aloscha"},
        {"Behar", "Behar"},
        {"Bechukotai", "Bechukosai"},
        {"Bereshit", "Bereishis"},
        {"Beshalach", "Beshalach"},
        {"Bo", "Bo"},
        {"Chayei Sara", "Chayei Sarah"},
        {"Chayei Sarahh", "Chayei Sarah"},
        {"Chukat", "Chukas"},
        {"Chukat-Balak", "Chukas-Balak"},
        {"Devarim", "Devarim"},
        {"Eikev", "Eikev"},
        {"Emor", "Emor"},
        {"ha-Moed", "HaMoed"},
        {"Ha'azinu", "Ha'azinu"},
        {"Ha’azinu", "Ha'azinu"},
        {"Ha’azinu", "Ha'azinu"},
        {"Haazinu", "Ha'azinu"},
        {"Kedoshim", "Kedoshim"},
        {"Ki Tavo", "Ki Savo"},
        {"Ki Teitzei", "Ki Seitzei"},
        {"Ki Tisa", "Ki Sisa"},
        {"Korach", "Korach"},
        {"Lech-Lecha", "Lech Lecha"},
        {"Masei", "Masei"},
        {"Matot", "Matos"},
        {"Matot-Masei", "Matos-Masei"},
        {"Metzora", "Metzora"},
        {"Miketz", "Mikeitz"},
        {"Mishpatim", "Mishpatim"},
        {"Naso", "Nasso"},
        {"Nitzavim", "Nitzavim"},
        {"Nitzavim-Vayeilech", "Nitzavim-Vayeilech"},
        {"Noach", "Noach"},
        {"Pekudei", "Pekudei"},
        {"Pinchas", "Pinchas"},
        {"Re’eh", "Re'eh"},
        {"Shabbat", "Shabbos"},
        {"Shemot", "Shemos"},
        {"Sh'lach", "Shelach"},
        {"Sh’lach", "Shelach"},
        {"Shmini", "Shemini"},
        {"Shoftim", "Shoftim"},
        {"Tazria", "Tazria"},
        {"Tazria-Metzora", "Tazria-Metzora"},
        {"Terumah", "Terumah"},
        {"Tetzaveh", "Tetzaveh"},
        {"Toldot", "Toldos"},
        {"Tzav", "Tzav"},
        {"Vaetchanan", "Va'eschanan"},
        {"Vayakhel", "Vayakhel"},
        {"Vayakhel-Pekudei", "Vayakhel-Pekudei"},
        {"Vayechi", "Vayechi"},
        {"Vayeilech", "Vayeilech"},
        {"Vayera", "Vayeira"},
        {"Vaera", "Va'eira"},
        {"Vayeshev", "Vayeishev"},
        {"Vayetzei", "Vayeitzei"},
        {"Vayigash", "Vayigash"},
        {"Vayikra", "Vayikra"},
        {"Vayishlach", "Vayishlach"},
        {"Yitro", "Yisro"},
        {"Vezot Haberakhah", "Vezos Haberachah"},
        {"V'Zos Habracha", "Vezos Haberachah"}
    }
    in ParashaMap;
